server.port=8080

# Supabase Session Pooler Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.igupnscnujtuckmoxmib
spring.datasource.password=Dillanmarquinq123

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.github.client-id=Ov23liTdvqHGvWwuWjuj
spring.security.oauth2.client.registration.github.client-secret=b811824c93f2b1fa8bbc6ac2f66ea4e0653cce13